navigation:
- text: Home
  url: /index.html
- text: History
  url: /history.html
- text: Uruguay
  url: /uruguay.html
- text: Technology
  url: /technology.html
- text: Results
  url: /results.html
- text: Further Reading
  url: /resources.html
