navigation:
- text: Home
  url: /index.html
- text: Uruguay
  url: /uruguay.html
- text: Technology
  url: /technology.html
- text: Implementation
  url: /implementation.html
- text: Further Reading
  url: /resources.html
